version: '3'
services:
  nsqlookupd:
    container_name: nsqlookupd
    image: ignatev/nsq
    command: /nsqlookupd
    networks:
      nsq_net:
        aliases:
          - nsqlookupd    
    ports:
      - "4160:4160"
      - "4161:4161"

  nsqd:
    container_name: nsqd
    image: ignatev/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    networks:
      nsq_net:
        aliases:
          - nsqd
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"

  nsqadmin:
    container_name: nsqadmin
    image: ignatev/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    networks:
      nsq_net:
        aliases:
          - nsqadm
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"

  mongodb:
    container_name: mongodb_go
    image: 'bitnami/mongodb:3.6'
    networks:
      nsq_net:
        aliases:
          - mongo
          - mongodb
          - mongodb_go
    ports:
      - "27018:27017"
    volumes:
      - 'mongodb_data_go:/bitnami'

networks:
  nsq_net:
    driver: bridge

volumes:
  mongodb_data_go: {}
